qonto/ember-autofocus-modifier

- .release-it.js
In order to be compatible with lerna changelog, and having the a unique env variable for both tools.
> chore: use GITHUB_AUTH instead of GITHUB_TOKEN

- package.json
- yarn.lock
> Remove deprecated ember-cli-htmlbars-inline-precompile

- .github/workflows/ci.yml
- .travis.yml
- package.json
This PR aims to drop `node 8` support as it has reaches is end of life
see https://nodejs.org/en/about/releases/
[//]: # "Add if relevant, remove if not"
* Update `package.json` to udpdate engines
* Update `.travis-ci.yml`
> 💥 Drop node 8 support 

- package.json
The changelog was not properly updated, as the maping with github labels wasn't done yet.
This MR fixes it.
> chore: update lerna-changelog labels for proper changelogs

- addon/modifiers/autofocus.js
- tests/integration/modifiers/autofocus-test.js
Hi, thanks for the modifier!
Thought it would be nice if the modifier supports textarea elements as well by default.
I couldn't find any related ticket or PR so I wasn't sure if support for textarea elements was omitted for a specific reason.
It seems to make sense to me, so thought I'd make a PR for it.
It's a behavioural change though, so might be "breaking" in some cases. As in, suddenly a textarea element has been given focus.
> Add default support for textarea elements

- tests/integration/modifiers/autofocus-test.js
Fix typo in 'should not focus inputs not related to the autofocused node' integration test
> Fix typo in integration test

- package.json
- yarn.lock
Could also have added them to the specific ember-try scenarios but that'd only make them break later on. As it's a devDep only I'd say this is the best way to go.
Internal change, non-breaking of course.
> Add auto-import/webpack dev dependencies to make beta/canary scenarios work

- addon/modifiers/autofocus.js
- package.json
- tests/integration/modifiers/autofocus-test.js
- yarn.lock
The rerender assertion would be triggered if we focus on a child where an `{{on "focus"}}` modifier is present that modifies a tracked variable (see the added test case/minimal reproduction). This is not reproducible with a classic Ember component, hence the added devDependencies for Glimmer components/tracking.
I _think_ it would be good enough to only schedule `childElement.focus()` on the next runloop rather than both cases, but we might want to keep things consistent, timing wise.
The most notable practical application where the described issue occurs is ember-power-select.
> Fix rerender assertion when focussing certain Glimmer components

- .github/workflows/ci.yml
- README.md
- config/ember-try.js
- package.json
- tests/integration/modifiers/autofocus-test.js
- yarn.lock
This drops support for Ember < 3.24. This is in line with the compatibility of [ember-modifier](https://github.com/ember-modifier/ember-modifier) allowing us to upgrade to ember-modifier v3 after this is merged.
> Drop support for Ember < 3.24

- addon/modifiers/autofocus.js
- tests/integration/modifiers/autofocus-test.js
This PR aims to add the support for the attribute [`readonly`](https://www.w3.org/TR/2010/WD-html5-20101019/common-input-element-attributes.html#attr-input-readonly), where only the `disabled` case was handled.
> Add readonly to default selector

- .github/workflows/ci.yml
This MR removes the double `pnpm install`: `NullVoxPopuli/action-setup-pnpm` already calls `pnpm install` and [expose an `args` input](https://github.com/NullVoxPopuli/action-setup-pnpm#args).
> Remove double pnpm installation

- .github/dependabot.yml
Updating the `interval` to `daily` so that we can test the new dependabot configuration quickly
> chore: update dependabot interval to daily

- ember-autofocus-modifier/.prettierignore
Adding the `.prettierignore` file to `ember-autofocus-modifier`.
This will be used subsequently in the following pull request: https://github.com/qonto/ember-autofocus-modifier/pull/432
> chore: add .prettierignore to ember-autofocus-modifier

- ember-autofocus-modifier/package.json
- pnpm-lock.yaml
Since our test suite runs test for specific ember versions (that are also [specified in our README](https://github.com/qonto/ember-autofocus-modifier#compatibility)) we're setting them explicitly in the `peerDependencies` for the package.
Related to https://github.com/qonto/ember-amount-input/pull/587.
> fix(peer-deps): explicitly set ember-source versions range

- ember-autofocus-modifier/package.json
- pnpm-lock.yaml
Removing `ember-source@5` from `peerDepencies` since we had multiple problems with it in the following PRs:
- https://github.com/qonto/ember-autofocus-modifier/pull/431
- https://github.com/qonto/ember-autofocus-modifier/pull/415
> chore: remove ember-source v5 from peerDependencies

- .github/workflows/ci.yml
- package.json
- pnpm-lock.yaml
- test-app/config/ember-try.js
- test-app/package.json
In this Pull Request I'm doing the following:
- Update test-app to `ember-source@5.3.0`. I was previously adding this here https://github.com/qonto/ember-autofocus-modifier/pull/447, but better to split this for added control and better review (e.g.: in case of revert a separate PR could be easier to manage)
- Add missing ember-try test scenarios for ember LTS version prior to `5.3.0`
- The override done on the root package.json is required to fix [this problem](https://github.com/qonto/ember-autofocus-modifier/actions/runs/6494674434/job/17638109873?pr=447#step:4:268) on the CI related to `embroider-*` jobs. This is recommended by the embroider docs: https://github.com/embroider-build/embroider/blob/main/docs/peer-dependency-resolution-issues.md
> chore: update test-app to ember-source@5.3.0

- ember-autofocus-modifier/.eslintrc.cjs
- test-app/.eslintrc.js
In this PR, we update the rules in our TS eslint config to allow the use of the `private` and `protected` keywords in TypeScript classes definition.
> feat(ts-lint): allow use of private and protected syntax for classes in .ts files

- ember-autofocus-modifier/.eslintrc.cjs
- ember-autofocus-modifier/package.json
- pnpm-lock.yaml
- test-app/.eslintrc.js
- test-app/package.json
Install and use our custom ESLint configuration found on https://github.com/qonto/eslint-config-typescript
The currently available version is a RC (Release Candidate) that we're testing on our public repos before making it stable.
> chore: install and use @qonto/eslint-config-typescript@1.0.0-rc.0

- README.md
In this PR, we add a section dedicated to TypeScript in README.md. See [ember-lottie](https://github.com/qonto/ember-lottie#typescript-usage) for reference.
> docs: add TypeScript usage section

- .github/workflows/ci.yml
- ember-autofocus-modifier/package.json
- pnpm-lock.yaml
- test-app/package.json
In this PR, we update `typescript` from `v5.2.2` to latest `v5.3.2`. We also add a new job for type checking the addon using TypeScript v5.2.
> chore(deps-dev): bump typescript from 5.2.2 to 5.3.2

- .release-it.js
- RELEASE.md
- package.json
- pnpm-lock.yaml
In this PR, we replace  `@release-it-plugins/lerna-changelog` with `@release-it/conventional-changelog` in order to leverage Conventional Commit messages and update the CHANGELOG seamlessly.
This makes the entire process even more straightforward, as no preparation work is required ahead of a new release.
The process has been tested locally, attempting a sample release with dummy features and a breaking change. CHANGELOG and versions would have been updated as expected.
Similar to https://github.com/qonto/ember-lottie/pull/322
> Add release it conventional changelog

- .github/workflows/release.yml
- .release-it.js
This PR adds a new workflow to delegate the package release to the CI.
The workflow can be dispatched only manually and will perform the following steps:
- Check out the code, including all history for all branches and tags.
- Verify that the workflow is triggered for the `main` branch, and abort if not.
- Set the Git user name and email to the person (or app) that initiated the workflow.
- Install dependencies.
- Trigger the release script.
> Add release workflow

- .github/workflows/release.yml
Fix the branch check so that we always start release from `master`.
> chore(release): fix workflow main branch check

- .github/workflows/ci.yml
- .github/workflows/release.yml
- package.json
- pnpm-lock.yaml
This MR adds a packageManager entry in the package.json to pin pnpm's version. This avoids duplication in CI workflows and hint multiple tools to use a specific pnpm version. (action-setup-pnpm, dependabot, corepack, etc...)
> chore: use packageManager entry in package.json

- ember-autofocus-modifier/src/modifiers/autofocus.ts
- test-app/tests/integration/modifiers/autofocus-test.ts
This PR tries to solve https://github.com/qonto/ember-autofocus-modifier/issues/522.
The fix has 2 main points.
First, the `Positional` argument should extend `Array<any>`. Therefore, it cannot be `undefined`. The first fix corresponds to:
```diff
- Positional: [string?] | undefined;
+ Positional: [string?];
```
This should resolve https://github.com/qonto/ember-autofocus-modifier/issues/522.
Then, by doing so, we encounter a type error in our integration tests file when we do something like:
```ts
<div {{autofocus disabled=false}}>
```
The error is: `Argument of type '{ [NamedArgs]: true; disabled: boolean; }' is not assignable to parameter of type 'string'.`
The issue we encounter is explained [here](https://github.com/typed-ember/glint/discussions/627#discussioncomment-7188233), and …
> fix(type): positional argument should extend `Array<any>`

- pnpm-lock.yaml
Embroider updates were blocked and a solution proposed was to use `pnpm dedupe`
> chore: dedupe pnpm lock file
